#!/usr/bin/env bash
# protect-files.sh — PreToolUse(Edit|Write)
#
# Blocks edits to files that must never be changed by an agent:
#   - .env and friends (real ones; .env.example / .template / .sample are fine)
#   - libs/data-access/api-types/src/lib/types.ts — generated from the API's OpenAPI
#     document; hand-editing it is silently undone by the next `npm run generate:api`
#   - the committed lockfile
#   - .claude/settings.json itself
#   - key material (.pem, .key, service-account JSON)
#
# Exit 2 blocks the tool call and explains why.

set -u

PAYLOAD="$(cat 2>/dev/null || true)"

json_str() {
  _key="$1"
  [ -z "${PAYLOAD:-}" ] && return 0
  if command -v jq >/dev/null 2>&1; then
    printf '%s' "$PAYLOAD" | jq -r --arg k "$_key" \
      'getpath($k | split(".")) // empty' 2>/dev/null && return 0
  fi
  if command -v python3 >/dev/null 2>&1; then
    printf '%s' "$PAYLOAD" | python3 -c '
import sys, json
try:
    d = json.load(sys.stdin)
except Exception:
    sys.exit(0)
for k in sys.argv[1].split("."):
    if isinstance(d, dict) and k in d:
        d = d[k]
    else:
        sys.exit(0)
print(d if isinstance(d, str) else json.dumps(d))
' "$_key" 2>/dev/null && return 0
  fi
  _leaf="${_key##*.}"
  printf '%s' "$PAYLOAD" \
    | sed -n "s/.*\"${_leaf}\"[[:space:]]*:[[:space:]]*\"\([^\"]*\)\".*/\1/p" \
    | head -n 1
}

FILE="$(json_str 'tool_input.file_path')"
[ -z "${FILE:-}" ] && FILE="$(json_str 'tool_input.notebook_path')"
[ -z "${FILE:-}" ] && exit 0

BASE="${FILE##*/}"

block() {
  cat >&2 <<EOF
BLOCKED by .claude/hooks/protect-files.sh

  File:   $FILE
  Reason: $1

  $2
EOF
  exit 2
}

# --- Environment files ------------------------------------------------------
case "$BASE" in
  .env.example|.env.template|.env.sample|.env.dist) ;;   # templates are fine
  .env|.env.*|*.env)
    block "environment files hold real credentials" \
          "Edit .env.example instead and tell the developer which variable to set."
    ;;
esac

# --- Generated API types ----------------------------------------------------
case "$FILE" in
  */libs/data-access/api-types/src/lib/types.ts|libs/data-access/api-types/src/lib/types.ts)
    block "api-types is generated from the API's OpenAPI document, not hand-written" \
          "Run 'npm run generate:api' (or /sync). If the shape you need is missing, the API contract has to change first."
    ;;
esac

# --- The dependency lockfile ------------------------------------------------
case "$BASE" in
  package-lock.json)
    if [ -e "$FILE" ]; then
      block "package-lock.json is generated by npm, not edited by hand" \
            "Run 'npm install <pkg>' (or 'npm ci' to restore it) and commit the resulting diff."
    fi
    ;;
esac

# --- The harness's own configuration ----------------------------------------
case "$FILE" in
  */.claude/settings.json|.claude/settings.json)
    block "settings.json wires the guardrails, including this hook" \
          "Changing it is a human decision. Use .claude/settings.local.json for personal overrides."
    ;;
esac

# --- Key material -----------------------------------------------------------
case "$BASE" in
  *.pem|*.p12|*.pfx|*.key|id_rsa|id_ed25519|*-service-account*.json|credentials.json)
    block "this looks like key material" \
          "Key material never lives in the repository. Reference it from the secret store."
    ;;
esac

exit 0
